version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run: node --version
      - run:
          name: Front End Install
          command: |
            npm run frontend:install
      - run:
          name: BackEnd Install
          command: |
            npm run backend:install
      - run:
          name: FrontEnd Build
          command: |
            npm run frontend:build
      - run:
          name: BackEnd Build
          command: |
            npm run backend:build
      - aws-cli/install
      - run:
          name: FrontEnd deploy
          command: |
            npm run frontend:deploy
      - aws-cli/install
      - eb/setup
      - run:
          name: BackEnd deploy
          command: |
            npm run backend:deploy
workFlows:
Deploying_Frontend_Backend:
  jobs:
    - frontend
    - backend
