version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: npm run deploy
  backend:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - eb/setup
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Build Server
          command: |-
            npm run build
      - aws-cli/install
      - run:
          name: Deploying
          command: |
            npm run deploy

workflows:
  Deploying_Frontend_&_Backend:
    jobs:
      - frontend
      - backend
